//AUTOGENERATED - DO NOT TOUCH!
public struct InputAction {
    public const int DirX = 0;
    public const int DirY = 1;
    public const int Jump = 2;
    public const int Action = 3;
    public const int Undo = 4;
    public const int Menu = 5;
    public const int Select1 = 6;
    public const int Select2 = 7;
    public const int Select3 = 8;
    public const int Select4 = 9;
    public const int Select5 = 10;
}
